# Generated by Django 3.2.5 on 2021-12-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trader', '0001_initial'),
        ('Stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='trader',
            field=models.ManyToManyField(to='Trader.Trader'),
        ),
    ]
